FROM python:3.12-slim

RUN pip install --no-cache-dir poetry
RUN poetry config virtualenvs.create false
WORKDIR /app
COPY pyproject.toml .
COPY poetry.lock .
RUN poetry install --only main --no-root
COPY . /app

CMD ["fastapi", "dev", "main.py", "--port", "8001", "--host", "0.0.0.0"]